# convert_assets.py
def generate_assets():
    header_content = """#ifndef ASSETS_H
#define ASSETS_H

// Auto-generated by convert_assets.py
#define GAME_TITLE "Celeste Classic (C++ Port)"
#define SCREEN_WIDTH 320
#define SCREEN_HEIGHT 240

// PICO-8 16-color palette mapped to 16-bit RGB565 values
const unsigned short PICO8_PALETTE[16] = {
    0x0000, // 0: Black
    0x1D13, // 1: Dark Blue
    0x78B5, // 2: Dark Purple
    0x02D1, // 3: Dark Green
    0xAB8B, // 4: Brown
    0x5F5B, // 5: Dark Gray
    0xC67A, // 6: Light Gray
    0xFFFC, // 7: White
    0xF808, // 8: Red
    0xFC00, // 9: Orange
    0xFFE0, // 10: Yellow
    0x07E0, // 11: Green
    0x2D7F, // 12: Blue
    0x83B3, // 13: Lavender
    0xFA12, // 14: Pink
    0xFDCF  // 15: Peach
};

#endif // ASSETS_H
"""
    with open("assets.h", "w") as f:
        f.write(header_content)
    print("Generated assets.h successfully.")

if __name__ == "__main__":
    generate_assets()
